server:
  port: 8080

spring:
  main:
    banner-mode: off
  application:
    name: resilience-app


# Resilience4j Configuration
resilience4j:
  retry:
    configs:
      default:
        max-attempts: 1
        wait-duration: 1000ms
    instances:
      # Used by @Retry annotation approach in TroubleMakerAdapter
      annotationRetryConfig:
        max-attempts: 5
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 1.5
        retry-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.net.SocketException
          - java.net.UnknownHostException
          - java.io.IOException
          - feign.RetryableException
          - feign.FeignException
          - feign.FeignException.ServiceUnavailable
          - feign.FeignException.InternalServerError
          - feign.FeignException.BadGateway
          - feign.FeignException.GatewayTimeout

# Application URLs and Configuration
app:
  troubleMaker:
    url: http://localhost:8081

  # Programmatic Retry Configuration
  programmaticRetryConfig:
    max-attempts: 5
    # Strategy options: standard-exponential, random-backoff, custom-interval
    strategy: "random-backoff"
    initial-interval: 200  # in milliseconds
    exponential-backoff-multiplier: 1.5
    randomization-factor: 0.5
    maxInterval: 10000  # in milliseconds (10 seconds)

    # Alternative configurations:
    # For standard-exponential strategy:
    # strategy: "standard-exponential"
    # initial-interval: 500
    # exponential-backoff-multiplier: 2.0

    # For custom-interval strategy:
    # strategy: "custom-interval"

    retry-exceptions:
      - java.net.ConnectException
      - java.net.SocketTimeoutException
      - java.net.SocketException
      - java.net.UnknownHostException
      - java.io.IOException
      - feign.RetryableException
      - feign.FeignException
      - feign.FeignException.ServiceUnavailable
      - feign.FeignException.InternalServerError
      - feign.FeignException.BadGateway
      - feign.FeignException.GatewayTimeout