server:
  port: 8080
spring:
  main:
    banner-mode: off
  application:
    name: service-a
  cloud:
    openfeign:
      client:
        config:
          serviceC:
            url: http://localhost:8082
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
resilience4j:
  retry:
    instances:
      serviceCRetry:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - feign.RetryableException
          - feign.FeignException
      troubleMakerRetry:
        max-attempts: 5
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 1.5
        retry-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - feign.RetryableException
          - feign.FeignException
app:
  serviceB:
    url: http://localhost:8081
  troubleMaker:
    url: http://localhost:8081
