server:
  port: 8080
spring:
  main:
    banner-mode: off
  application:
    name: client-a
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  cloud:
    openfeign:
      client:
        config:
          serviceB:
            url: http://localhost:8081
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
          serviceC:
            url: http://localhost:8082
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
resilience4j:
  retry:
    instances:
      serviceBRetry:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2